.setup_windows:
  interruptible: true
  tags:
    - windows
  before_script:
    - call D:\Gitlab-Runner\Miniconda3\Library\bin\conda.bat activate
    - conda.exe config --set show_channel_urls true
    - conda.exe config --add channels conda-forge
    - conda.exe config --remove-key channels
    - conda.exe config --add channels conda-forge
    - conda.exe config --add channels https://conda.anaconda.org/t/%BINSTAR_TOKEN_READONLY%/ramonaoptics
    - conda.exe install -n root --yes conda-build conda conda-forge-ci-setup
    - conda.exe config --set anaconda_upload no
    - conda.exe config --show
    - call git submodule init
    - call git submodule update
    - conda.exe build purge

.setup_linux:
  interruptible: true
  image: condaforge/linux-anvil-comp7
  tags:
    - linux
  before_script:
    - source /opt/conda/etc/profile.d/conda.sh
    - conda config --set show_channel_urls true
    - conda config --remove-key channels
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels https://conda.anaconda.org/t/${BINSTAR_TOKEN_READONLY}/ramonaoptics
    - conda install -n root --yes conda-build conda conda-forge-ci-setup
    - conda config --set anaconda_upload no
    - conda config --show
    - git submodule init
    - git submodule update
    # Don't know why this is needed, but it is
    # https://github.com/ContinuumIO/anaconda-issues/issues/9190#issuecomment-384697849
    - /usr/bin/sudo -n yum install -y mesa-libGL

build_linux:
  extends: .setup_linux
  interruptible: true
  stage: build
  script:
    - conda build .

deploy_linux:
  extends: .setup_linux
  interruptible: true
  stage: deploy
  only:
    - tags
  script:
    # tests were already run in the previous step, this just avoid the need for artifacts.
    - conda build --no-test .
    - upload_or_check_non_existence . ramonaoptics

static_checking_linux:
  extends: .setup_linux
  interruptible: true
  # let this test run in parallel
  stage: build
  script:
    - conda create --name owl_runner_pyilluminate --yes flake8 mypy
    - source activate owl_runner_pyilluminate
    - python -m flake8 pyilluminate setup.py
    # - python -m mypy pyilluminate
