.setup:
  before_script:
    - call C:\Gitlab-Runner\Miniconda3\Library\bin\conda.bat activate
    - conda.exe update --override-channels -c defaults -c conda-forge conda
    - conda.exe config --set show_channel_urls true
    - conda.exe info
    - conda.exe config --remove-key channels
    # I think we are already logged in
    #- call anaconda login --username ramonaoptics --password %ANACONDA_PASSWORD% --hostname gitlab-windows-runner
    - conda.exe config --add channels defaults
    - conda.exe config --add channels conda-forge
    - conda.exe config --add channels ramonaoptics
    - conda.exe info
    - conda.exe remove --name owl-runner --all --force --yes --offline
    - conda.exe create --name owl-runner --yes
    - call activate.bat owl-runner

run:
  extends: .setup
  tags:
    - windows
  stage: build
  script:
    - conda.exe install --file requirements.txt
    - python.exe -m pip install . --no-deps
    - cd ..
    - python.exe -c "import pyilluminate; print(pyilluminate.__version__)"

static_checking:
  extends: .setup
  tags:
    - windows
  stage: test
  script:
    - conda.exe install flake8 mypy
    - python.exe -m flake8 pyilluminate setup.py
    - python.exe -m mypy pyilluminate


conda_deploy:
  # Only deploy if a new tag is created
  only:
    - tags
  tags:
    - windows
  stage: deploy
  script:
    - call C:\Gitlab-Runner\Miniconda3\Library\bin\conda.bat activate
    - conda.exe config --set show_channel_urls true
    - conda.exe config --remove-key channels
    - conda.exe config --add channels defaults
    - conda.exe config --add channels conda-forge
    - conda.exe config --add channels ramonaoptics
    - conda.exe install -n root --yes conda-build
    - conda.exe config --set anaconda_upload yes
    - conda.exe build .
    - conda.exe config --set anaconda_upload no
