pipelines:
  tags:
    release-*:
      - step:
         name: Deploy
         image: markharfouche/python_flake8
         deployment: production
         script:
           - flake8 setup.py */*.py
           - python3 setup.py clean -a bdist_wheel
           - for file in `ls dist`; do curl -X POST --user "${BB_AUTH_USER}":"${BB_AUTH_PASSWORD}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/${file}"; done

  custom:
    build_and_test:
      - step:
          name: Build and test
          image: markharfouche/python_flake8
          script:
            - python3 setup.py clean -a bdist_wheel
            - flake8 setup.py */*.py
