pipelines:
  tags:
    release-*:
      - step:
         name: Deploy
         image: markharfouche/miniconda3
         deployment: production
         script:
           - flake8 setup.py */*.py
           - # python3 setup.py clean -a bdist_wheel
           - conda build .
           - # dropbox_uploader.sh upload $CONDA_PREFIX/conda-bld/noarch/*.tar.bz2 pyilluminate/noarch/

  custom:
    build_and_test:
      - step:
          name: Build and test
          image: markharfouche/miniconda3
          script:
            - flake8 setup.py */*.py
            - python3 setup.py clean -a bdist_wheel
