# Basic versioneer, I don't want to run the setup.py before things are required
{% if environ.get('GIT_DESCRIBE_NUMBER') == '0' %}
{% set version = environ.get('GIT_DESCRIBE_TAG')[8:] %}
{% else %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '')[8:] + '+' + environ.get('GIT_DESCRIBE_NUMBER', '') %}
{% endif %}

package:
  name: pyilluminate
  version: {{ version }}

source:
  path: .

build:
  number: 1
  include_recipe: False
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - pyserial
    - xarray
    - numpy

about:
  home: www.ramonaoptics.com
  license: BSD
  license_file: LICENSE

test:
 imports:
   - pyilluminate
