{% set data = load_setup_py_data() %}

package:
  name: pyilluminate
  version: {{ data.get('version') }}

source:
  path: .

build:
  number: 0
  include_recipe: False
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - pyserial
    - xarray

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENSE

test:
 imports:
   - pyilluminate
